version: "3"
services:
  web:
    build: .
    container_name: flask_container
    ports:
      - 5000:5000
  db:
    image: "ddalgiie/courses-db"
    ports:
      - 1433:1433
    container_name: mssqldb_container